<?php

use Phalcon\Http\Response;

if (isset($this->session->login)) {
    if ($this->view->message == 'success') {
        echo "<h1>Login Successful</h1>";
        echo "<h3>" . $this->date . "<h3>";
        echo $this->tag->linkTo(["login/dashboard", "Logout", 'class' => 'btn btn-primary']);
    } else {
        $response = new Response();
        $response->setStatusCode(403, 'authentication failed');
        $response->setContent("Please enter a valid Email and Password");
        $response->send();
        echo "<br>" . $this->tag->linkTo(["login", "Go Back", 'class' => 'btn btn-primary']);
    }
}
else{
    $this->response->redirect("login");
}
